# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Arm_Joint1
      - Arm_Joint2
      - Arm_Joint3
      - Arm_Joint4
      - Arm_Joint5
      
  hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Grip_Joint
