# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    learm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

learm_group_controller:
  ros__parameters:
    joints:
      - Arm_Joint1
      - Arm_Joint2
      - Arm_Joint3
      - Arm_Joint4
      - Arm_Joint5
      - Grip_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity