# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - learm_group_controller

  learm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Arm_Joint1
      - Arm_Joint2
      - Arm_Joint3
      - Arm_Joint4
      - Arm_Joint5